apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sprintboot2"
  description: "sprintboot2"
  annotations:
    github.com/project-slug: "kaparwan/sprintboot2"
    backstage.io/techdocs-ref: github:https://github.com/kaparwan/sprintboot2
spec:
  type: service
  lifecycle: experimental
  owner: "kaparwan"
